"""
Phase 4 Milestone 6: Remote Scripts Generator

Generate remote-server scripts for reproducible GPU suite execution.
"""

from pathlib import Path
import shlex
from typing import Any


def _script_relative_path(path: str, *, project_dir: str | None = None) -> str:
    """Return a path that is valid after the generated script changes directory."""
    if not project_dir:
        return path

    project_name = Path(project_dir).name
    path_obj = Path(path)

    if path_obj.is_absolute():
        try:
            return str(path_obj.relative_to(project_dir))
        except ValueError:
            return path

    parts = path_obj.parts
    if project_name == "gaam_memory_training" and parts and parts[0] == "gaam_memory_training":
        return str(Path(*parts[1:]))

    return path


def generate_remote_run_script(
    suite_config: dict[str, Any],
    *,
    suite_config_path: str = "suite_config.resolved.json",
    conda_env: str | None = None,
    project_dir: str | None = None,
    output_path: Path,
) -> None:
    """
    Generate bash script for remote GPU suite execution.

    Args:
        suite_config: Suite configuration dictionary
        conda_env: Conda environment name (optional)
        project_dir: Project directory path (optional)
        output_path: Output path for generated script
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append("# Remote GPU Benchmark Suite Execution Script")
    lines.append(f"# Suite: {suite_config.get('suite_name', 'Unknown')}")
    lines.append("# Generated by Phase 4 Milestone 6")
    lines.append("")

    # Environment activation
    if conda_env:
        lines.append(f"# Activate conda environment")
        lines.append(f"source $(conda info --base)/etc/profile.d/conda.sh")
        lines.append(f"conda activate {shlex.quote(conda_env)}")
        lines.append("")

    # Set working directory
    if project_dir:
        lines.append(f"# Set working directory")
        lines.append(f"cd {shlex.quote(project_dir)}")
        lines.append("")

    # Set PYTHONPATH
    lines.append("# Set PYTHONPATH")
    lines.append('export PYTHONPATH="$PWD:${PYTHONPATH:-}"')
    lines.append("")

    # Check dependencies
    lines.append("# Check dependencies")
    lines.append("echo 'Checking Python dependencies...'")
    lines.append("python -c 'import torch; import transformers; print(f\"PyTorch: {torch.__version__}\"); print(f\"Transformers: {transformers.__version__}\")'")
    lines.append("")

    # Backend readiness check
    trainer_backend = suite_config.get("trainer_backend", "dry_run")
    memory_builder_model = suite_config.get("memory_builder_model_path", "")
    question_agent_model = suite_config.get("question_agent_model_path", "")
    answerer_model = suite_config.get("answerer_model_path", "")
    require_cuda = suite_config.get("require_cuda", False)

    lines.append("# Backend readiness check")
    lines.append("echo 'Checking backend readiness...'")
    lines.append("python scripts/check_phase4_backend_readiness.py \\")
    lines.append(f"  --trainer_backend {trainer_backend} \\")

    if memory_builder_model:
        lines.append(f"  --memory_builder_model_path {shlex.quote(memory_builder_model)} \\")

    if question_agent_model:
        lines.append(f"  --question_agent_model_path {shlex.quote(question_agent_model)} \\")

    if answerer_model:
        lines.append(f"  --answerer_model_path {shlex.quote(answerer_model)} \\")

    if require_cuda:
        lines.append("  --require_cuda \\")

    lines.append("  || { echo 'Backend not ready'; exit 4; }")
    lines.append("")

    # Run benchmark suite
    lines.append("# Run benchmark suite")
    lines.append("echo 'Starting benchmark suite...'")

    output_dir = suite_config.get("output_dir", "outputs/benchmark_suite")
    seeds = suite_config.get("seeds", [0])
    script_suite_config_path = _script_relative_path(
        suite_config_path,
        project_dir=project_dir,
    )

    lines.append("python scripts/run_phase4_benchmark_suite.py \\")
    lines.append(f"  --suite_config {shlex.quote(script_suite_config_path)} \\")
    lines.append(f"  --output_dir {shlex.quote(output_dir)} \\")
    lines.append(f"  --seeds {' '.join(map(str, seeds))} \\")
    lines.append(f"  --trainer_backend {trainer_backend} \\")

    if memory_builder_model:
        lines.append(f"  --memory_builder_model_path {shlex.quote(memory_builder_model)} \\")

    if question_agent_model:
        lines.append(f"  --question_agent_model_path {shlex.quote(question_agent_model)} \\")

    if answerer_model:
        lines.append(f"  --answerer_model_path {shlex.quote(answerer_model)} \\")

    lines.append("  --resume")
    lines.append("")

    # Aggregate results
    lines.append("# Aggregate results")
    lines.append("echo 'Aggregating metrics...'")
    lines.append("python scripts/aggregate_phase4_benchmark_suite.py \\")
    lines.append(f"  --suite_dir {shlex.quote(output_dir)}")
    lines.append("")

    # Build release package
    lines.append("# Build release package")
    lines.append("echo 'Building release package...'")
    lines.append("python scripts/build_phase4_release_package.py \\")
    lines.append(f"  --suite_dir {shlex.quote(output_dir)}")
    lines.append("")

    # Verify artifacts
    lines.append("# Verify artifacts")
    lines.append("echo 'Verifying release artifacts...'")
    lines.append("python scripts/verify_phase4_artifacts.py \\")
    lines.append(f"  --release_dir {shlex.quote(str(Path(output_dir) / 'release'))} \\")
    lines.append("  --strict")
    lines.append("")

    lines.append("echo 'Benchmark suite complete!'")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # Make executable
    output_path.chmod(0o755)


def generate_slurm_script(
    suite_config: dict[str, Any],
    *,
    job_name: str | None = None,
    partition: str = "gpu",
    nodes: int = 1,
    gpus_per_node: int = 1,
    cpus_per_task: int = 8,
    mem_gb: int = 32,
    time_limit: str = "24:00:00",
    conda_env: str | None = None,
    project_dir: str | None = None,
    output_path: Path,
) -> None:
    """
    Generate SLURM batch script for cluster execution.

    Args:
        suite_config: Suite configuration dictionary
        job_name: SLURM job name
        partition: SLURM partition
        nodes: Number of nodes
        gpus_per_node: GPUs per node
        cpus_per_task: CPUs per task
        mem_gb: Memory in GB
        time_limit: Time limit (HH:MM:SS)
        conda_env: Conda environment name
        project_dir: Project directory path
        output_path: Output path for generated script
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if job_name is None:
        job_name = suite_config.get("suite_name", "gaam_benchmark")

    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append("")
    lines.append(f"#SBATCH --job-name={job_name}")
    lines.append(f"#SBATCH --partition={partition}")
    lines.append(f"#SBATCH --nodes={nodes}")
    lines.append(f"#SBATCH --gres=gpu:{gpus_per_node}")
    lines.append(f"#SBATCH --cpus-per-task={cpus_per_task}")
    lines.append(f"#SBATCH --mem={mem_gb}G")
    lines.append(f"#SBATCH --time={time_limit}")
    lines.append(f"#SBATCH --output=slurm-%j.out")
    lines.append(f"#SBATCH --error=slurm-%j.err")
    lines.append("")
    lines.append("set -euo pipefail")
    lines.append("")

    # Load modules (common on HPC clusters)
    lines.append("# Load modules")
    lines.append("# module load cuda/11.8  # Uncomment and adjust as needed")
    lines.append("")

    # Environment activation
    if conda_env:
        lines.append(f"# Activate conda environment")
        lines.append(f"source $(conda info --base)/etc/profile.d/conda.sh")
        lines.append(f"conda activate {shlex.quote(conda_env)}")
        lines.append("")

    # Set working directory
    if project_dir:
        lines.append(f"# Set working directory")
        lines.append(f"cd {shlex.quote(project_dir)}")
        lines.append("")

    lines.append("# Run benchmark suite")
    lines.append("bash scripts/generated/run_benchmark_suite.sh")
    lines.append("")
    lines.append("echo 'SLURM job complete!'")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # Make executable
    output_path.chmod(0o755)
